name: Generate Neon Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # ĞºĞ°Ğ¶Ğ´Ñ‹Ğ¹ Ğ´ĞµĞ½ÑŒ Ğ² Ğ¿Ğ¾Ğ»Ğ½Ğ¾Ñ‡ÑŒ
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§© Checkout code
        uses: actions/checkout@v3

      - name: ğŸ Generate snake animation (Neon Night)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: GhostDainy
          outputs: dist/snake.svg
          palette: "github-dark,cyan-magenta"

      - name: ğŸš€ Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
