name: Generate Neon Snake Animation ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # Ğ·Ğ°Ğ¿ÑƒÑĞºĞ°ĞµÑ‚ÑÑ ĞºĞ°Ğ¶Ğ´Ñ‹Ğ¹ Ğ´ĞµĞ½ÑŒ Ğ² Ğ¿Ğ¾Ğ»Ğ½Ğ¾Ñ‡ÑŒ
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ§© Checkout code
        uses: actions/checkout@v4

      - name: ğŸ Generate snake animation (Neon Night)
        uses: Platane/snk@v3
        with:
          github_user_name: GhostDainy
          outputs: dist/snake.svg

      - name: ğŸš€ Publish snake animation to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
